Repository lint-todo/utils, pull requests merged in 2020-10, with the labels that each got.

#6 Add prepare script to package.json scripts.
  package.json
Labels: internal

#16 Changes storage mechanism to use filePath based directories to store todo files.
  README.md
  __tests__/__fixtures__/fixtures.ts
  __tests__/__fixtures__/single-file-no-errors.json
  __tests__/io-test.ts
  src/builders.ts
  src/index.ts
  src/io.ts
  src/types/index.ts
Labels: breaking

#20 Adding API to determine if storage directory exists
  __tests__/io-test.ts
  src/index.ts
  src/io.ts
Labels: enhancement
