Repository lint-todo/utils, pull requests merged in 2021-06, with the labels that each got.

#213 Extends todo configuration to support configuring days to decay by rule ID.
  __tests__/__utils__/fake-project.ts
  __tests__/builders-test.ts
  __tests__/todo-config-test.ts
  src/builders.ts
  src/todo-config.ts
  src/types/index.ts
Labels: breaking

#225 Update docs with new getTodoConfig API changes
  README.md
  src/todo-config.ts
Labels: documentation

#237 Tweak `getDatePart` to use UTC date
  src/date-utils.ts
Labels: bug

#242 Adds new validateConfig function
  README.md
  __tests__/todo-config-test.ts
  src/todo-config.ts
Labels: enhancement

#247 Exporting new date-utils APIs
  src/index.ts
Labels: bug

#250 Renaming FilePath type to improve code readability
  README.md
  src/builders.ts
  src/io.ts
  src/types/index.ts
Labels: breaking, internal

#252 Adding expanded todo batching functionality to account for fuzzy matching
  .eslintrc
  README.md
  __tests__/__utils__/build-todo-data.ts
  __tests__/__utils__/get-fixture.ts
  __tests__/builders-test.ts
  __tests__/io-test.ts
  __tests__/todo-batch-generator-test.ts
  src/builders.ts
  src/index.ts
  src/io.ts
  src/todo-batch-generator.ts
  src/todo-matcher.ts
  src/types/index.ts
Labels: breaking, enhancement
